#!/bin/sh

# Save me in /usr/loca/bin, and make sure it's executables (chmod +x eagle)
# Note: sometimes QT_AUTO_SCREEN_SCALE_FACTOR=0 is helpful, too.

export LIBGL_ALWAYS_SOFTWARE=1 QT_SCALE_FACTOR=0.5
path/to/eagle-9.3.0/eagle "$@"

